from scrapy import cmdline
# cmdline.execute("scrapy crawl bristolMasters".split())
# cmdline.execute("scrapy crawl strathMasters".split())
# cmdline.execute("scrapy crawl manchesterMasters".split())
# cmdline.execute("scrapy crawl durhamMasters".split())
# cmdline.execute("scrapy crawl kingsMasters".split())
# cmdline.execute("scrapy crawl manchesterResearchMasters".split())
# cmdline.execute("scrapy crawl strathResearchMasters".split())
# cmdline.execute("scrapy crawl astonMasters".split())

# cmdline.execute("scrapy crawl salfordBen".split())
# cmdline.execute("scrapy crawl salfordMastersTaught".split())
# cmdline.execute("scrapy crawl salfordMastersResearch".split())
# cmdline.execute("scrapy crawl bathspaBen".split())
# cmdline.execute("scrapy crawl hertsBen".split())
# cmdline.execute("scrapy crawl uclanBen".split())
# cmdline.execute("scrapy crawl cardiffmetBen".split())
# cmdline.execute("scrapy crawl cardiffmetMasterTaught".split())
# cmdline.execute("scrapy crawl hopeMastersTaught".split())
# cmdline.execute("scrapy crawl portMastersTaught".split())
# cmdline.execute("scrapy crawl portMastersResearch".split())
# cmdline.execute("scrapy crawl portMastersResearch1".split())
# cmdline.execute("scrapy crawl lincolnBen".split())
# cmdline.execute("scrapy crawl lincolnMastersTaught".split())
# cmdline.execute("scrapy crawl lincolnMastersResearch".split())
# cmdline.execute("scrapy crawl uwlMastersTaught".split())
# cmdline.execute("scrapy crawl bathspaMastersTaught".split())
# cmdline.execute("scrapy crawl uclanMastersTaught".split())
# cmdline.execute("scrapy crawl hertsMastersTaught".split())
# cmdline.execute("scrapy crawl hertsMastersResearch".split())

# 2018/3/23
# cmdline.execute("scrapy crawl sheffieldBen".split())
# cmdline.execute("scrapy crawl dundeeBen".split())
cmdline.execute("scrapy crawl newcastleBen".split())

list1 = ["Bachelor of Aviation (Flying)",
"Bachelor of Aviation (Management)",
"Bachelor of Art Theory",
"Bachelor of Environmental Management",
"Bachelor of Art Theory / Bachelor of Arts",
"Bachelor of Actuarial Studies / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Exercise Physiology",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) / Master of Biomedical Engineering ",
"Bachelor of Environmental Management / Bachelor of Arts",
"Bachelor of Art Theory / Bachelor of Social Research and Policy",
"Bachelor of Advanced Science (Hons) / Bachelor of Laws",
"Bachelor of Media (Communication and Journalism)",
"Bachelor of Medical Studies / Doctor of Medicine",
"Bachelor of Commerce",
"Bachelor of Material Science and Engineering (Honours) / Masters of Biomedical Engineering ",
"Bachelor of Life Sciences",
"Bachelor of Design (Honours)",
"Bachelor of Art Theory / Bachelor of Laws",
"Bachelor of Media (Public Relations and Advertising)",
"Bachelor of Medical Studies / Doctor of Medicine / Bachelor of Arts",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Chemical Engineering ",
"Bachelor of Biotechnology (Hons)",
"Bachelor of Design (Honours) / Bachelor of Media in Public Relations and Advertising",
"Bachelor of Arts & Business / Bachelor of Laws",
"Bachelor of Media (Screen and Sound Production)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Industrial Chemistry",
"Bachelor of Medicinal Chemistry (Hons)",
"Bachelor of Fine Arts (Honours)",
"Bachelor of Arts / Bachelor of Laws",
"Bachelor of Music",
"Bachelor of Actuarial Studies",
"Bachelor of Food Science (Honours)",
"Bachelor of Nanoscience (Hons)",
"Bachelor of Fine Arts / Bachelor of Arts",
"Bachelor of City Planning (Hons) / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Civil Engineering with Architecture)",
"Bachelor of Fine Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce / Bachelor of Laws",
"Bachelor of Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Civil Engineering ",
"Bachelor of Engineering (Hons) in Materials Science and Engineering",
"Bachelor of Media Arts (Honours)",
"Bachelor of Criminology & Criminal Justice / Bachelor of Laws",
"Bachelor of Commerce / Bachelor of Education (Secondary)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Civil Engineering ",
"Bachelor of Engineering (Hons) in Materials Science and Engineering / Bachelor of Commerce",
"Bachelor of Economics / Bachelor of Laws",
"Bachelor of Design (Honours) / Bachelor of Education (Secondary)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Environmental Engineering ",
"Bachelor of Materials Science and Engineering (Hons) / Engineering Science",
"Bachelor of Engineering (Hons) / Bachelor of Laws",
"Bachelor of Economics / Bachelor of Education (Secondary)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Geospatial Engineering ",
"Bachelor of Science (Advanced Mathematics) (Hons)",
"Bachelor of Fine Arts / Bachelor of Laws",
"Bachelor of Fine Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Surveying ",
"Bachelor of Science (Advanced Mathematics) (Hons) / Bachelor of Arts",
"Bachelor of International Studies / Bachelor of Laws",
"Bachelor of Media Arts (Honours) / Bachelor of Education (Secondary)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Surveying",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Engineering (Hons)",
"Bachelor of Media (Communication & Journalism) / Bachelor of Laws",
"Bachelor of Music / Bachelor of Education (Secondary)",
"Bachelor of Economics",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Science (Computer Science) (Hons)",
"Bachelor of Media (Public Relations & Advertising) / Bachelor of Laws",
"Bachelor of Science / Bachelor of Education (Secondary)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Computer Engineering ",
"Bachelor of Vision Science / Master of Clinical Optometry",
"Bachelor of Media (Screen & Sound Production) / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Software Engineering ",
"Bachelor of Advanced Science (Hons)",
"Bachelor of Medicinal Chemistry (Hons) / Bachelor of Laws",
"Bachelor of International Studies",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Science (Computer Science)",
"Bachelor of Advanced Science (Hons) / Bachelor of Arts",
"Bachelor of Music / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Bioinformatics Engineering",
"Bachelor of Advanced Science (Hons) / Bachelor of Engineering (Hons)",
"Bachelor of Psychological Science / Bachelor of Laws",
"Bachelor of Arts and Business",
"Bachelor of Actuarial Studies",
"Bachelor of Science (Computer Science)",
"Bachelor of Advanced Science (Hons) / Bachelor of Fine Arts",
"Bachelor of Psychology (Hons) / Bachelor of Laws",
"Bachelor of Criminology and Criminal Justice",
"Bachelor of Commerce",
"Bachelor of Science (Computer Science) / Bachelor of Media Arts (Hons) ",
"Bachelor of Advanced Science (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science & Business / Bachelor of Laws",
"Bachelor of International Studies",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Electrical Engineering ",
"Bachelor of Advanced Science (Hons)/Social Research and Policy",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Laws",
"Bachelor of Social Research and Policy",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Telecommunications Engineering ",
"Bachelor of Science",
"Bachelor of Science (Computer Science) / Bachelor of Laws",
"Bachelor of Social Work (Honours)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering / Master of Engineering in Electrical Engineering ",
"Bachelor of Science (Honours)",
"Bachelor of Science / Bachelor of Laws",
"Bachelor of Commerce",
"Bachelor of Advanced Mathematics (Hons) / Bachelor of Engineering (Honours)",
"Bachelor of Science (International)",
"Bachelor of Social Research & Policy / Bachelor of Laws",
"Bachelor of Commerce (International)",
"Bachelor of Advanced Mathematics (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science / Bachelor of Arts",
"Bachelor of Social Work (Hons) / Bachelor of Laws",
"Bachelor of Economics",
"Bachelor of Advanced Science (Hons) / Bachelor of Engineering (Honours)",
"Bachelor of Science / Bachelor of Fine Arts",
"Bachelor of Information Systems",
"Bachelor of Advanced Science (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science / Bachelor of Social Research and Policy",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce/Bachelor of Science (Computer Science)",
"Bachelor of Science and Business",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) / Bachelor of Laws ",
"Bachelor of Psychological Science",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Commerce",
"Bachelor of Psychological Science (Honours)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) / Bachelor of Science",
"Bachelor of Psychology (Hons)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Hons) / Bachelor of Arts ",
"Bachelor of Commerce",
"Bachelor of Music /Bachelor of Engineering (Honours)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Aerospace Engineering",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Mechanical and Manufacturing Engineering",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Mechanical Engineering",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Mechatronic Engineering",
"Bachelor of Commerce (International)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Mining Engineering",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Petroleum Engineering ",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Photovoltaics and Solar Energy ",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Renewable Energy Engineering ",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce",
"Bachelor of Commerce (International)",
"Bachelor of Economics",]
valuelist = ["41,760",
"41,760",
"32,400",
"41,760",
"32,400",
"40,080",
"32,160",
"42,030",
"39,960",
"41,760",
"39,060",
"32,280",
"41,280",
"32,160",
"66,480",
"39,360",
"41,760",
"41,760",
"32,400",
"34,260",
"32,160",
"66,480",
"39,360",
"41,760",
"41,760",
"32,280",
"35,760",
"32,160",
"39,360",
"41,760",
"41,760",
"32,400",
"34,080",
"33,840",
"39,960",
"41,760",
"41,760",
"32,400",
"36,000",
"32,160",
"39,960",
"41,760",
"33,480",
"39,480",
"33,000",
"39,360",
"41,760",
"41,760",
"32,400",
"34,080",
"37,980",
"39,360",
"41,760",
"41,760",
"39,480",
"32,760",
"39,360",
"41,760",
"41,760",
"41,280",
"37,980",
"39,960",
"41,760",
"41,760",
"34,260",
"33,480",
"39,360",
"41,760",
"39,360",
"35,130",
"32,760",
"39,360",
"41,760",
"41,760",
"34,080",
"33,840",
"39,360",
"41,760",
"34,080",
"39,780",
"39,960",
"41,760",
"41,760",
"34,080",
"32,160",
"39,360",
"41,760",
"41,760",
"41,280",
"33,840",
"39,360",
"41,760",
"39,360",
"36,840",
"32,160",
"39,360",
"41,760",
"41,760",
"40,800",
"35,760",
"39,960",
"41,760",
"37,080",
"40,800",
"32,160",
"39,360",
"41,760",
"41,760",
"40,560",
"33,840",
"39,360",
"41,760",
"36,960",
"41,280",
"32,160",
"39,360",
"41,760",
"41,760",
"41,280",
"33,360",
"39,960",
"41,760",
"41,760",
"41,280",
"39,360",
"41,760",
"41,760",
"34,080",
"39,360",
"41,760",
"36,960",
"35,280",
"39,360",
"41,760",
"37,080",
"39,360",
"41,760",
"36,960",
"39,960",
"40,860",
"41,160",
"39,360",
"41,280",
"41,760",
"39,360",
"41,760",
"41,760",
"39,360",
"41,760",
"41,760",
"39,960",
"41,760",
"39,360",
"37,800",
"39,360",
"41,760",
"39,360",
"41,760",
"39,960",
"41,760",
"39,360",
"41,760",
"39,360",
"39,360",
"41,760",
"39,960",
"39,360",
"41,760",
"39,360",
"41,760",
"39,360",
"41,760",
"39,960",
"39,360",
"39,360",
"39,360",]
resultDict = {}

for i in range(len(list1)):
    resultDict[list1[i]] = valuelist[i]

# print(resultDict)
l = ["Sheffield University Management School",
"Department of Animal and Plant Sciences",
"Department of Animal and Plant Sciences",
"Department of Animal and Plant Sciences",
"Department of Biomedical Science",
"Department of Biomedical Science",
"Bioengineering",
"Bioengineering",
"Department of Materials Science and Engineering",
"Bioengineering",
"Department of Materials Science and Engineering",
"Department of Animal and Plant Sciences",
"Bioengineering",
"Department of Biomedical Science",
"Department of Civil and Structural Engineering",
"Sheffield University Management School",
"Department of Animal and Plant Sciences",
"Bioengineering",
"Department of Physics and Astronomy",
"Department of Automatic Control and Systems Engineering",
"Department of Urban Studies and Planning",
"Department of Urban Studies and Planning",
"Department of Animal and Plant Sciences",
"Department of Physics and Astronomy",
"Department of Automatic Control and Systems Engineering",
"Department of Automatic Control and Systems Engineering",
"Department of Physics and Astronomy",
"Department of Automatic Control and Systems Engineering",
"Department of Human Communication Sciences",
"Department of Automatic Control and Systems Engineering",
"Department of Automatic Control and Systems Engineering",
"Department of Automatic Control and Systems Engineering",
"Department of Civil and Structural Engineering",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"Russian Studies",
"Department of Human Communication Sciences",
"Russian Studies",
"Russian Studies",
"Department of Sociological Studies",
"Department of Computer Science",
"Department of Sociological Studies",
"Department of Automatic Control and Systems Engineering",
"Department of Sociological Studies",
"Russian Studies",
"Russian Studies",
"Russian Studies",
"Russian Studies",
"Russian Studies",
"Sheffield Methods Institute",
"Russian Studies",
"Department of Politics",
"Department of Politics",
"Department of Archaeology",
"Russian Studies",
"Department of Physics and Astronomy",
"Department of Psychology",
"Department of Physics and Astronomy",
"Department of Animal and Plant Sciences",
"Department of Physics and Astronomy",
"Department of Politics",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Animal and Plant Sciences",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Physics and Astronomy",
"Department of Philosophy",
"Department of Philosophy",
"Department of Philosophy",
"Department of Oncology and Metabolism",
"Department of Music",
"School of Nursing and Midwifery",
"Department of Music",
"Department of Music",
"Department of Music",
"Department of Physics and Astronomy",
"Department of Music",
"Department of Music",
"Department of Molecular Biology and Biotechnology",
"Department of Physics and Astronomy",
"Department of Molecular Biology and Biotechnology",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Molecular Biology and Biotechnology",
"School of Languages and Cultures",
"Academic Unit of Medical Education",
"Department of Materials Science and Engineering",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Automatic Control and Systems Engineering",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Automatic Control and Systems Engineering",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Automatic Control and Systems Engineering",
"Department of Automatic Control and Systems Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"Department of Mechanical Engineering",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"Department of Mechanical Engineering",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"School of Mathematics and Statistics",
"Department of Materials Science and Engineering",
"Department of Materials Science and Engineering",
"School of Mathematics and Statistics",
"Department of Materials Science and Engineering",
"School of English",
"School of Mathematics and Statistics",
"School of English",
"Department of Materials Science and Engineering",
"School of Law",
"School of Law",
"Department of Materials Science and Engineering",
"Department of Materials Science and Engineering",
"School of English",
"School of English",
"School of Law",
"School of Law",
"Department of Landscape",
"School of East Asian Studies",
"Department of Landscape",
"School of East Asian Studies",
"School of Law",
"Department of Journalism Studies",
"School of Law",
"School of East Asian Studies",
"School of East Asian Studies",
"Department of Politics",
"School of Law",
"School of East Asian Studies",
"School of East Asian Studies",
"Department of History",
"Sheffield University Management School",
"Department of History",
"Department of History",
"Department of History",
"Department of History",
"School of East Asian Studies",
"Department of History",
"Department of History",
"Hispanic Studies",
"Hispanic Studies",
"Hispanic Studies",
"Hispanic Studies",
"Hispanic Studies",
"Hispanic Studies",
"Hispanic Studies",
"School of Nursing and Midwifery",
"Department of History",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Germanic Studies",
"Department of Geography",
"Germanic Studies",
"Department of Molecular Biology and Biotechnology",
"Department of Urban Studies and Planning",
"Department of Geography",
"Department of Geography",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"French Studies",
"School of Mathematics and Statistics",
"Department of Geography",
"Department of Geography",
"French Studies",
"French Studies",
"School of English",
"School of English",
"School of English",
"School of English",
"School of English",
"School of English",
"School of English",
"School of English",
"Engineering IPO",
"School of English",
"School of English",
"Department of Electronic and Electrical Engineering",
"School of English",
"Engineering IPO",
"School of English",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"School of Education",
"Department of Electronic and Electrical Engineering",
"Department of Economics",
"Department of Economics",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Economics",
"Department of Economics",
"Department of Economics",
"Department of Economics",
"Department of Electronic and Electrical Engineering",
"School of East Asian Studies",
"Department of Electronic and Electrical Engineering",
"Department of Electronic and Electrical Engineering",
"Department of Animal and Plant Sciences",
"Department of Sociological Studies",
"Department of Electronic and Electrical Engineering",
"School of Clinical Dentistry",
"Department of Electronic and Electrical Engineering",
"Department of Automatic Control and Systems Engineering",
"School of Law",
"Department of Animal and Plant Sciences",
"Department of Automatic Control and Systems Engineering",
"Department of Automatic Control and Systems Engineering",
"Department of Computer Science",
"Department of Automatic Control and Systems Engineering",
"Department of Computer Science",
"Department of Computer Science",
"School of Clinical Dentistry",
"Arts and Humanities IPO",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"Department of Civil and Structural Engineering",
"Department of Civil and Structural Engineering",
"Department of Archaeology",
"Department of Civil and Structural Engineering",
"Department of Computer Science",
"Department of Civil and Structural Engineering",
"Department of Civil and Structural Engineering",
"Department of Civil and Structural Engineering",
"School of East Asian Studies",
"School of East Asian Studies",
"School of East Asian Studies",
"School of East Asian Studies",
"School of East Asian Studies",
"School of East Asian Studies",
"Department of Chemistry",
"Department of Civil and Structural Engineering",
"Department of Civil and Structural Engineering",
"Department of Chemistry",
"School of East Asian Studies",
"School of East Asian Studies",
"Department of Chemistry",
"Department of Chemistry",
"Department of Chemical and Biological Engineering",
"Department of Chemistry",
"Department of Chemical and Biological Engineering",
"Department of Chemistry",
"Department of Chemical and Biological Engineering",
"Department of Chemical and Biological Engineering",
"Department of Chemical and Biological Engineering",
"Department of Chemistry",
"Department of Chemical and Biological Engineering",
"Sheffield University Management School",
"Department of Chemical and Biological Engineering",
"Department of Biomedical Science",
"Sheffield University Management School",
"Sheffield University Management School",
"Sheffield University Management School",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Biomedical Science",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Molecular Biology and Biotechnology",
"Department of Computer Science",
"Department of Molecular Biology and Biotechnology",
"Department of Computer Science",
"Department of Computer Science",
"Department of Computer Science",
"School of Architecture",
"Department of Chemical and Biological Engineering",
"Department of Civil and Structural Engineering",
"Department of Chemical and Biological Engineering",
"Department of Civil and Structural Engineering",
"Sheffield Methods Institute",
"Department of Archaeology",
"School of Architecture",
"Department of Archaeology",
"Engineering IPO",
"Aerospace Engineering",
"Department of Archaeology",
"Aerospace Engineering",
"Aerospace Engineering",
"Aerospace Engineering",
"Department of Archaeology",
"Sheffield Methods Institute",
"Aerospace Engineering",
"Sheffield University Management School",
"Aerospace Engineering",
"Aerospace Engineering",]
l = list(set(l))
# print(l)
# print(len(l))